#### Numpy

In [87]:
import numpy as np

In [67]:
a=np.array([[1,4,3,6,7,8],[1,2,3,2,3,2]])
print (a)

[[1 4 3 6 7 8]
 [1 2 3 2 3 2]]


In [68]:
b=np.array([[[2,4,6],[8,9,0]],[[3,4,5],[1,2,3]]],dtype='int8')
print (b)


[[[2 4 6]
  [8 9 0]]

 [[3 4 5]
  [1 2 3]]]


In [83]:
a.ndim

2

In [84]:
a.shape

(2, 6)

In [85]:
b.shape

(2, 2, 3)

In [41]:
a.dtype

dtype('int32')

In [86]:
b.dtype

dtype('int8')

In [50]:
a.itemsize

4

In [53]:
a.size

3

In [54]:
arraysize= a.itemsize*a.size
arraysize

12

#### Accessing Data And Manipulating

In [59]:
a[0,1]


np.int32(4)

In [69]:
a[0,:]

array([1, 4, 3, 6, 7, 8])

In [63]:
a[:,0]

array([1, 1])

In [74]:
a[1,2:-1]

array([3, 2, 3])

In [76]:
a[:,3]=[2,6]
print(a)

[[1 4 3 2 7 8]
 [1 2 3 6 3 2]]


In [78]:
b[0,1,1]

np.int8(9)

In [82]:
b[1,:,:]=[[1,2,3],[4,5,6]]
b

array([[[2, 4, 6],
        [8, 9, 0]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int8)

#### Different Types Of Array

In [95]:
c= np.empty_like(a)
c

array([[      1967684517704,                  58,                   0,
                          0,        498216206336, 3904177109877286251],
       [3258409518118232422, 7306303339165331767, 7146428876852374838,
        3763146046611731767, 7162263158367990838, 8463219666660455541]])

In [97]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [102]:
np.zeros((3,2,5),dtype='int8')

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]], dtype=int8)

In [103]:
np.full((2,4),68)

array([[68, 68, 68, 68],
       [68, 68, 68, 68]])

In [104]:
np.full_like(a,6)

array([[6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6]])

In [107]:
np.full(b.shape,99)

array([[[99, 99, 99],
        [99, 99, 99]],

       [[99, 99, 99],
        [99, 99, 99]]])

In [112]:
np.random.rand(3,5)

array([[0.9760917 , 0.9557683 , 0.23697632, 0.29957404, 0.49449473],
       [0.71275708, 0.45893705, 0.33742691, 0.96423172, 0.25752211],
       [0.12782044, 0.57413264, 0.86156778, 0.04667105, 0.64791051]])

In [125]:
np.random.randint(-5,9,size=(3,3))

array([[ 1,  2,  5],
       [-1,  2,  8],
       [ 3,  5, -5]], dtype=int32)

In [126]:
np.identity((5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [130]:
np.repeat(a,3,axis=0)

array([[1, 4, 3, 2, 7, 8],
       [1, 4, 3, 2, 7, 8],
       [1, 4, 3, 2, 7, 8],
       [1, 2, 3, 6, 3, 2],
       [1, 2, 3, 6, 3, 2],
       [1, 2, 3, 6, 3, 2]])

In [143]:
x=np.ones((5,5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [144]:
y=np.zeros((3,3))
y[1,1]=9
y

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [147]:
x[1:-1,1:-1]=y
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])