In [2]:
import torch
import torch.nn as nn

In [15]:
torch.manual_seed(42)
inputs=torch.tensor([1.0,2.0,3.0])

In [16]:
inputs

tensor([1., 2., 3.])

In [17]:
neuron=nn.Linear(in_features=3,out_features=1)
output=neuron(inputs)

In [18]:
output

tensor([1.5244], grad_fn=<ViewBackward0>)

In [19]:
neuron.weight @ inputs+ neuron.bias

tensor([1.5244], grad_fn=<AddBackward0>)

In [20]:
neuron.bias

Parameter containing:
tensor([0.5304], requires_grad=True)

In [21]:
neuron.weight

Parameter containing:
tensor([[ 0.4414,  0.4792, -0.1353]], requires_grad=True)